"""empty message

Revision ID: 48c038b8173f
Revises: e99a43caa41b
Create Date: 2023-08-30 18:08:48.311551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c038b8173f'
down_revision = 'e99a43caa41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_favourite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favourite_id')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_character', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_planets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_vehicles', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_starships', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'characters', ['id_character'], ['id'])
        batch_op.create_foreign_key(None, 'starships', ['id_starships'], ['id'])
        batch_op.create_foreign_key(None, 'vehicles', ['id_vehicles'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['id_planets'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_favourite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favourite_id')

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.drop_constraint('starships_favourite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favourite_id')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('vehicles_favourite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favourite_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('vehicles_favourite_id_fkey', 'favorite', ['favourite_id'], ['id'])

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('starships_favourite_id_fkey', 'favorite', ['favourite_id'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('planets_favourite_id_fkey', 'favorite', ['favourite_id'], ['id'])

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_starships')
        batch_op.drop_column('id_vehicles')
        batch_op.drop_column('id_planets')
        batch_op.drop_column('id_character')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('characters_favourite_id_fkey', 'favorite', ['favourite_id'], ['id'])

    # ### end Alembic commands ###
