"""empty message

Revision ID: bd360ea238b9
Revises: 48c038b8173f
Create Date: 2023-08-30 18:33:45.119781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd360ea238b9'
down_revision = '48c038b8173f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_characters', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_id_character_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'characters', ['id_characters'], ['id'])
        batch_op.drop_column('id_character')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_character', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_id_character_fkey', 'characters', ['id_character'], ['id'])
        batch_op.drop_column('id_characters')

    # ### end Alembic commands ###
